### ISSUE TITLE
App folder bug

### ISSUE THREAD

**Issue by RushingAlien** [aunetx/blur-my-shell#109]
App folder blur gets re-enabled after locking session even when it is disabled in the settings menu. Had to tick and then re-disable the app folder option manually ever lock session.

**Comment by aunetx** [comment]
Yeah, it happens to me too! I will see what causes this :)

**Comment by aunetx** [comment]
Fixed in last commit, will push when possible :)

**Comment by RushingAlien** [comment]
Many thanks!

**Comment by RushingAlien** [comment]
Hello, I am sorry to report that this bug still occurs in gnome 40.

**Comment by aunetx** [comment]
I don't see what could cause this now, did this happen before the upgrade?

**Comment by RushingAlien** [comment]
I'm sorry it works fine now, I don't know what could be caused it again all of a sudden.

**Comment by aunetx** [comment]
OK cool! Don't worry, it's better to reopen it than ignore the issue :)
