### ISSUE TITLE
Blur is bugged in Dash to Dock

### ISSUE THREAD

**Issue by DeicPro** [aunetx/blur-my-shell#154]
Whatever setting you do makes the same result when Blur enabled for Dash

[Wayland]
![Captura de pantalla de 2021-11-28 14-45-45](https://user-images.githubusercontent.com/12710770/143771471-8b2dd03c-dfed-4681-88d6-ba521e131af1.png)

[Wayland] When open a non-favorite app
![Captura de pantalla de 2021-11-28 14-51-52](https://user-images.githubusercontent.com/12710770/143771458-50b36d34-512b-4d34-b65c-cc919e25ece3.png)

[Xorg]
![Captura de pantalla de 2021-11-28 14-44-03](https://user-images.githubusercontent.com/12710770/143771517-12928435-3cfe-4a2c-aefd-f7dc2e53e999.png)

Ubuntu 21.10
Gnome 40.5
Dash to Dock v71 no transparency, custom color, small borders option

**Comment by DeicPro** [comment]
Just in case: I read the bug about rounded corners, but this bug occurs in any case
![Captura de pantalla de 2021-11-28 15-42-27](https://user-images.githubusercontent.com/12710770/143772736-6c964073-5835-4af5-923e-fa4e1c490030.png)

**Comment by Movisivi** [comment]
Blur is broken for dash-to-dock. Disable dash transparency in extensions app

**Comment by longmathemagician** [comment]
Is there a specific version of dash to dock that it does more or less work on?

**Comment by Movisivi** [comment]
No. Honestly I just disabled dash to dock and use GNOME stock. I realized I alt-tab between apps anyway so the dash is useless for me. I do miss holding Windows key + 1, 2, 3, 4 to open apps though

**Comment by aunetx** [comment]
Fixed with last commits!

**Comment by mi16087** [comment]
This issue is not fixed for me with last commit to main (EndeavourOS gnom 41.2), can't make straight corners, also gets darker around the icons and not the whole dock when on mouse hover (was not set to do such a ting and is not best shown on screenshot 2).
![Screenshot from 2022-01-07 23-01-40](https://user-images.githubusercontent.com/44554049/148614172-36f14ab2-90d2-4d63-b2ba-3167d32df815.png)
on mouse hover:
![Screenshot from 2022-01-07 23-03-14](https://user-images.githubusercontent.com/44554049/148614176-6f9143e7-1c9b-4c24-adf1-0ca81b6ee8fb.png)
dash to dock ->appearence ->use buillt-in theme:
![Screenshot from 2022-01-07 23-04-11](https://user-images.githubusercontent.com/44554049/148614187-06d73e3d-1f04-4d40-9787-00f7bb3361b3.png)
and just in case, whitesur shell theme:
![Screenshot from 2022-01-08 00-44-12](https://user-images.githubusercontent.com/44554049/148620970-28cf9870-d41e-437b-ac8e-76b65aa37f1e.png)
