### ISSUE TITLE
Static blur for dash-to-panel too small

### ISSUE THREAD

**Issue by chidniu** [aunetx/blur-my-shell#243]
On an ultra-wide screen the static blur does not cover the whole panel:

![Screenshot from 2022-05-14 13-46-39](https://user-images.githubusercontent.com/5339604/168424322-67d7269a-ada3-41ce-a9f0-6cb22a9bb1f5.png)

I am using blur-my-shell 35 on Gnome 42.1-1 (Manjaro Linux).

**Comment by aunetx** [comment]
I think this should be fixed with latest updates as dash-to-panel works quite well now

**Comment by chidniu** [comment]
I tried to confirm the fix but the problem still persists (blur-my-shell 58 and Gnome 44).

**Comment by aunetx** [comment]
Thanks, will see what I can do!

**Comment by kernelb00t** [comment]
@chidniu does it still happens? I can't repro on 4k monitor with gnome 46, Fullscreen avoider from gnome exts, and BMS v62
