### ISSUE TITLE
After locking and unlocking workspace, dynamic dash-to-panel blur has wrong dimensions

### ISSUE THREAD

**Issue by chidniu** [aunetx/blur-my-shell#244]
When enabling the dynamic blur on dash-to-panel it works perfectly but as soon as I lock and unlock the workspace, the blurred area shrinks:

![Screenshot from 2022-05-14 13-53-22](https://user-images.githubusercontent.com/5339604/168424638-f3a1154a-72a1-4e1f-8cd3-f0029ffe8d68.png)

If I disable and enable the blur from the extensions options it works perfectly fine again (until I lock the screen the next time).

I am using blur-my-shell 35 on Gnome 42.1-1 (Manjaro Linux)

**Comment by aunetx** [comment]
I think this should be fixed with latest updates as dash-to-panel works quite well now, please reopen if not

**Comment by chidniu** [comment]
Just tested this real quick. The problem persists (blur-my-shell 58 and Gnome 44.0-1, still on Manjaro Linux).
