### ISSUE TITLE
Version 44 incorrect applications blur

### ISSUE THREAD

**Issue by seppiofish** [aunetx/blur-my-shell#357]
Just upgraded to version 44 (still gnome 42) and noticed this issue with applications blur. It incorrectly blurs just a portion of the window and also goes out of bound. I tried whit multiple applications and it is always like this. It seems that the blurred rectangle is always the same size regardless of the windows size or type. I've been using applications blur on a couple of windows for some weeks to test it and I never saw this bug before upgrading to version 44.

![Screenshot from 2022-10-04 18-22-30](https://user-images.githubusercontent.com/20034870/193879064-e187f560-1a8f-4993-b751-09617fe65478.png)
![Screenshot from 2022-10-04 18-57-52](https://user-images.githubusercontent.com/20034870/193880870-a314daf1-54ec-4f16-9ddf-93575f1e86bb.png)

**Comment by CorvetteCole** [comment]
I cannot reproduce this on my test setup unfortunately, are you on X11 or Wayland?

**Comment by seppiofish** [comment]
@CorvetteCole I was, and still am, using Wayland. Based on similar issues other people had I suspect this happens because I use fractional scaling in gnome. The issue is still present for me but has slightly changed actually: the outlining blurred rectangle is still present and varies quite a bit in dimensions depending on the application but the windows are no longer transparent. I can provide further details if you need them.

**Comment by aunetx** [comment]
I just fixed this in last commit, will push to extensions.gnome.org for gnome 45 very soon

**Comment by seppiola** [comment]
@aunetx Recently updated to gnome 45 and blur my shell 51 but nothing has changed, the issue is still present exactly as in the old screenshots above. I updated today to version 52 of the extensions but it's still the same.
