### ISSUE TITLE
Wayland Fractional scaling set area for application blurring wrong

### ISSUE THREAD

**Issue by mauriciobc** [aunetx/blur-my-shell#362]
After applying the window application blur, if you move the window, the size for the blurring area is not correctly set.
System is Fedora 36, using Nvidia drivers.
![Blur_my_shell_wayland_fractional_scaling](https://user-images.githubusercontent.com/5098821/195991442-c18d993a-e2ff-424d-8323-b0550e9e93c3.png)

**Comment by CorvetteCole** [comment]
I cannot reproduce this on Wayland with fractional scaling using Mesa with AMD graphics. Will try to obtain Nvidia hardware to test on.

**Comment by CorvetteCole** [comment]
This may end up being an external issue, but I will still investigate it for now

**Comment by mauriciobc** [comment]
Thanks! Let me know if I can be of any assistance.

**Comment by dnut** [comment]
I'm having the same issue in gnome 42.5 with intel graphics when a secondary monitor is scaled at 125% and my primary monitor is scaled at 100%. It only occurs when the window is created or resized within the secondary monitor.

**Comment by CorvetteCole** [comment]
that's interesting, both my monitors use the same scaling so that could be a source of buggage

**Comment by mauriciobc** [comment]
I do have two monitors with different scaling settings. I tested turning settings to 100% and it seems to fix the problem, even after setting it back to 125%.

**Comment by RaduTek** [comment]
Can confirm this issue is occurring on Ubuntu 22.04 with Gnome 43.1 and the latest version of blur my shell. Here the blur is positioned wrong by default, only switching scaling to 100% and back to the fractional value gets the blur positioned right, but only until you resize a window.

**Comment by Kombatant** [comment]
Confirming with Gnome 43 and Manjaro, latest Mesa 23/7900XTX user. I have two monitors, one has 125% scaling, one 175% and I have this issue. As soon as I change any monitor's scaling scaling setting to 100%, everything works fine.

**Comment by jamu85** [comment]
can reproduce it on gnome 44 on arch with amdgpu
2 monitors, both at 125%

**Comment by aunetx** [comment]
I fixed this in last commit, could you please test it?

**Comment by aunetx** [comment]
This is fixed in last release

**Comment by bertin0** [comment]
This is still present for me with a dual monitor setup, on a 4k external display.

Arch with gnome 45.1-1 and extension version 54

**Comment by dnut** [comment]
> This is still present for me with a dual monitor setup, on a 4k external display.
> 
> Arch with gnome 45.1-1 and extension version 54

same here

**Comment by alesya-h** [comment]
Still present for me as well. NixOS, Gnome 45, extension 54, integrated Intel GPU, scale factor 150%

**Comment by Christmaswreath** [comment]
Yep, still there!
RTX 3070,
Fedora,
Gnome 45,
Scale factor 125%.

**Comment by Suyashtnt** [comment]
Also have it
AMD iGPU
NixOS
Gnome 45
Scale factor 125%
