### ISSUE TITLE
Application Blur not working Gnome 43.2 Wayland

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [aunetx/blur-my-shell#391]
Although the window rules seem to apply for transparency, blur seems to have no effect.

**Comment by KCGD** [comment]
Same issue here. Gnome wayland 43.2. Works perfectly on xorg

**Comment by hrqmonteiro** [comment]
> Same issue here. Gnome wayland 43.2. Works perfectly on xorg

In here it doesn't work perfectly, i have issues with the round corners, you have this as well?

![Screenshot from 2023-01-04 16-28-55](https://user-images.githubusercontent.com/17055027/210638482-be5e45b9-00da-424b-b232-bfec7012b47f.png)

**Comment by KCGD** [comment]
I have the corner issue in xorg yeah. No blur at all in wayland (for applications)

**Comment by KCGD** [comment]
Application blur seems to work in the overview in wayland, but going back to normal view makes it go away again

![Blur in overview works](https://user-images.githubusercontent.com/48497186/210842435-95d083b9-4852-4108-9c5e-0ffcaec30363.png)

**Comment by acerspyro** [comment]
I also sometimes get the corner issue when using the Rounded Window Corners extension by @yilozt

It works on some windows, and doesn't on others. I also don't get any blur whatsoever under Wayland.

It also looks like the corners get turned inwards when I take a screenshot, and screenshots show the windows as having literal PNG transparency.

![image](https://user-images.githubusercontent.com/4400999/210863534-69292c59-be00-4fa4-b3ac-46e477ad5590.png)

![image](https://user-images.githubusercontent.com/4400999/210863410-f7bd79b8-a31b-4e88-a976-a1a4edce4c5a.png)

![image](https://user-images.githubusercontent.com/4400999/210863487-db955150-d61b-494e-8d10-206b23a0007b.png)

**Comment by KCGD** [comment]
Oddly enough, gnome's terminal blurs just fine under wayland (tested on intel and nvidia), and so does kitty. I configured both of those to have transparent backgrounds, so could that have something to do with it?
 
![Screenshot from 2023-01-05 17-38-33](https://user-images.githubusercontent.com/48497186/210893767-08605af8-5d18-46e1-9803-2952a0a80f78.png)

**Comment by acerspyro** [comment]
I don't have access to the old GNOME terminal as I think it's been removed from Fedora 37's repos, but it doesn't work on Console or Tilix for me on Wayland.

**Comment by CorvetteCole** [comment]
Application blur seems to work for me on Mutter & Gnome 43.3 + Wayland. So hard to fix these issues without being able to reproduce them :/

**Comment by EvianMcKeown** [comment]
Having the same issue. I would be glad to provide any output or config files or whatever would help to identify the issue. 
When rounded window corners is enabled together with BMS - I get transparency, but no blur. (using nvidia and intel)

The following video and image are with rounded window corners disabled.

[Screencast from 2023-04-27 18-02-56.webm](https://user-images.githubusercontent.com/125868373/234921183-de76dd30-5f68-44b7-9e6b-2b421c6ad1ac.webm)


![Screenshot from 2023-04-27 18-04-28](https://user-images.githubusercontent.com/125868373/234920792-4104d27e-ec72-4318-97ae-38713c121acd.png)

Then with rounded window corners enabled: (transparency, but no blur)
![Screenshot from 2023-04-27 18-07-49](https://user-images.githubusercontent.com/125868373/234922086-d48dfbb2-cbb5-41e8-ae0d-58df049fdd71.png)

**Comment by aunetx** [comment]
It may work a little bit better now, as I fixed some opacity and scaling issues... Could some of you try it from the last commit?

**Comment by aunetx** [comment]
Duplicate of #358, and it should be fixed now (but needs testing...)

**Comment by bertin0** [comment]
For me this issue is still present with gnome 45 and extension version 43 (dual monitor setup 1080p laptop with 4k external monitor set as primary with 150% scaling)
