### ISSUE TITLE
Gnome 44 - Blurring not working for workspace thumbnails

### ISSUE THREAD

**Issue by lakotamm** [aunetx/blur-my-shell#415]
I decided to test the extension on Gnome 44 and I encountered an issue - workspace thumbnails are not blurred. This is with default settings and no other extension active. On Gnome 43 the workspace thumbnails are blurred by default so I would expect the same behavior on Gnome 44.

![Screenshot from 2023-03-02 23-25-06](https://user-images.githubusercontent.com/6938962/222573814-e813a060-6e13-4698-898e-b2ed4432d867.png)

**Comment by user1-github** [comment]
Gnome 44 is about to release and my distro (OpenSuse Microos which is a rolling release) is one of the fastest in bringing new major Gnome versions. If this is currently the only issue with Blur my Shell on Gnome 44, I can live with that for a while. 
What did you do to make it work under Gnome 44? Did you edit metadata.json and added the number 44 under "shell-version"?

**Comment by lakotamm** [comment]
> @lakotamm Gnome 44 is about to release and my distro (OpenSuse Microos which is a rolling release) is one of the fastest in bringing new major Gnome versions. If this is currently the only issue with Blur my Shell on Gnome 44, I can live with that for a while. What did you do to make it work under Gnome 44? Did you edit metadata.json and added the number 44 under "shell-version"?

Correct, that's the only thing I changed.

I am still waiting until this gets fixed, afterwards I will update to Fedora 38.

**Comment by carlwgeorge** [comment]
> What did you do to make it work under Gnome 44? Did you edit metadata.json and added the number 44 under "shell-version"?

Another option is to run `dconf write /org/gnome/shell/disable-extension-version-validation true`, which allows loading extensions despite what their metadata.json file claims to be compatible with.

**Comment by aunetx** [comment]
Hello, thanks for opening this issue, I currently don't have gnome 44 so can't test it... I will add support for it in the metadata, but this bug will need to stay opened some more time :/

**Comment by sounak-kun** [comment]
Bumping this issue since it's been opened some time, and it's the most frequently visible one.

**Comment by aunetx** [comment]
I am under gnome 44 now, and I don't experience this bug... Do you have a custom theme for the shell?

**Comment by aunetx** [comment]
I just fixed this, now the workspace thumbnail background colour is linked to components' style in overview

**Comment by sounak-kun** [comment]
@aunetx Sorry for waking up a closed issue, but you may have forgot to merge fb34041. Still having this issue in Gnome 45, Blur my Shell version 53.
