### ISSUE TITLE
Black line under the top bar

### ISSUE THREAD

**Issue by danielpabeda** [aunetx/blur-my-shell#428]
I have top bar blur permanently enabled, and after the 44.1 gnome update a black line appeared below the bar. Am I the only one with this problem? How to treat?

Screen: https://ibb.co/3S5y0Rm

**Comment by hrqmonteiro** [comment]
Same thing here. Started an hour ago, and i can't understand why.

![Screenshot from 2023-05-01 10-34-54](https://user-images.githubusercontent.com/17055027/235458901-7bf348bf-5293-439d-8f9e-00bf30d8e390.png)

But it probably will stay like this, the owner of the repo is not answering any of the last 200 issues.

**Comment by aunetx** [comment]
I just fixed it in last commit thanks

**Comment by NettoHikari** [comment]
![image](https://github.com/aunetx/blur-my-shell/assets/8510368/7ad074d3-810b-47ed-ae88-678afbd122ac)

Unfortunately, this still happens when a theme is applied (in this case, [Arc](https://github.com/jnsh/arc-theme)).

**Comment by hrqmonteiro** [comment]
> ![image](https://user-images.githubusercontent.com/8510368/267014507-7ad074d3-810b-47ed-ae88-678afbd122ac.png)
> 
> Unfortunately, this still happens when a theme is applied (in this case, [Arc](https://github.com/jnsh/arc-theme)).

Probably cause the theme css overwrite blur my shell's css
