### ISSUE TITLE
bug on startup with multiple monitors with different resolutions

### ISSUE THREAD

**Issue by sjhaleprogrammer** [aunetx/blur-my-shell#503]
![Screenshot from 2023-11-26 07-40-01](https://github.com/aunetx/blur-my-shell/assets/60676867/77bc1d84-56ed-4767-ba30-d1457895afb7)
only occurs on 1440p from what I've seen

**Comment by sjhaleprogrammer** [comment]
i think this issue caused by a delay in the startup of my main montior 

```
enable() {
    const checkMonitors = () => {
        const allMonitorsConnected = Main.layoutManager.monitors.every(
            monitor => monitor.is_connected() && monitor.is_primary()
        );

        if (!allMonitorsConnected) {
            // If not all monitors are connected, wait and check again
            this._log("Not all monitors are on and connected. Waiting...");
            Mainloop.timeout_add_seconds(1, checkMonitors);
            return;
        }

        // All monitors are on and connected, proceed with enabling the blur
        this._log("All monitors are on and connected. Blurring top panel.");

        // Rest of the enable method...

        this.enabled = true;
    };

    // Start the initial check
    checkMonitors();
}
```


something like this might fix it

**Comment by matteodev8** [comment]
I am having the same issue on my 2560x1080 monitor

**Comment by sjhaleprogrammer** [comment]
Is it connected to a laptop

**Comment by sjhaleprogrammer** [comment]
One gpu ? Right and does the montior that has the problem turn on later

**Comment by matteodev8** [comment]
> One gpu ? Right and does the montior that has the problem turn on later

2 GPUs, but only the RTX 3060 is used for displays, the GT 1030 is not used for driving the monitors.

I can't really tell, but my graphics card initializes the ultrawide monitor first, dunno about Linux

**Comment by coralof** [comment]
I am also experiencing this issue on Fedora 39 with Gnome 45.2. And I can confirm that I'm on a dual screen setup (with my laptop and one external display). Display is connected to a dock, which in turn goes through Thunderbolt to the laptop.

Laptop: 2256x1504
Monitor: 1920x1080

It happens right after I login, but will go away if I lock the screen and sign back in again.

**Comment by philipraets** [comment]
I have 3 monitors ( 2 monitors 2560x1440, 1 monitor 1920x1200). If I have all three enabled, I have this issue. If I disable the smaller monitor, everything is ok.

following tickets are all related:
#517
#513
#476

**Comment by RyzenDew** [comment]
@aunetx not sure if you have seen this issue or not i mentioned this to you while 45 was being worked on

**Comment by aunetx** [comment]
@RyzenDew yes, sorry for the silence... The problem is I don't have another monitor to test the changes I might do to correct this, but this week I may have one so if I find time, I will try to fix this (among other things)!

**Comment by TobiPeterG** [comment]
@aunetx I have this issue as well, should you need a tester, hmu :)

**Comment by SecMeyo** [comment]
did some further testing with display arrangements while logging out to reset the extension

this arrangement results in an issue:
![image](https://github.com/aunetx/blur-my-shell/assets/10670024/9d954692-ff6d-48f3-a89a-51e4da28d106)

while this does not:
![image](https://github.com/aunetx/blur-my-shell/assets/10670024/6bdb64f1-f40b-46c4-99df-8b8248e82206)

**Comment by aunetx** [comment]
Hello, could you try runnning blur-my-shell from the PR #546? I changed the way multiple monitors are managed so it should be better (maybe, I couldn't test it on multiple monitors hehe)

**Comment by schardev** [comment]
Yep. Having the same issue. I have the exact same setup as @coralof although I'm on Arch Linux + GNOME 46.1.

**Comment by thvlio** [comment]
I'm also having this issue. I'm using Ubuntu 24.04 (GNOME 46). Using extension version 62. When I was using Ubuntu 22.04 (GNOME 42), extension version 47, this wasn't happening, if it helps at all. This is my layout:
![s1](https://github.com/aunetx/blur-my-shell/assets/12574737/60b30b37-2d0d-4552-9737-45e9c107877c)

I ran a few tests using different layouts, screenshots were taken from the primary monitor, hope it helps (and that GitHub doesn't destroy the table):

| LAYOUT | RES 1 | RES 2 | RESULT |
|:------:|:-----:|:-----:|:------:|
| ![s1](https://github.com/aunetx/blur-my-shell/assets/12574737/60b30b37-2d0d-4552-9737-45e9c107877c) | 1080x1920 | 1920x1080 | ![p1](https://github.com/aunetx/blur-my-shell/assets/12574737/bc0a18d0-a994-4b02-9d22-ceee8fff7ead) |
| ![s2](https://github.com/aunetx/blur-my-shell/assets/12574737/456e5c60-44d6-4004-bf66-5bd523b89c82) | 720x1280 | 1920x1080 | ![p2](https://github.com/aunetx/blur-my-shell/assets/12574737/0233ffe8-2184-444e-9823-880da05b5be6) |
| ![s3](https://github.com/aunetx/blur-my-shell/assets/12574737/58ffdeef-629d-4f02-9b25-6097078737ff) | 1920x1080 | 1920x1080 | ![p3](https://github.com/aunetx/blur-my-shell/assets/12574737/0b9a517e-fa09-4fbc-8bef-1be03794059c) |
| ![s4](https://github.com/aunetx/blur-my-shell/assets/12574737/e3b59324-8743-4259-a203-f2a03e8b7496) | 1080x1920 | 1920x1080 | ![p4](https://github.com/aunetx/blur-my-shell/assets/12574737/61433ae2-cab9-4075-83be-af241683d204) |
| ![s5](https://github.com/aunetx/blur-my-shell/assets/12574737/eac0f8a9-0166-44b9-8054-142bac298064) | 1080x1920 | 1920x1080 | ![p5](https://github.com/aunetx/blur-my-shell/assets/12574737/d11984c1-ceab-44c6-8d48-8509552b9214) |

Seems to me, at least on my 2 monitor setup, that the width info is always coming from the leftmost monitor. But I don't know the inner workings of the extension so can't say for sure.

A quick way I found to reproduce the issue (besides logging out and in again) is to switch which monitor is the primary. Whenever I go from (1) to (2) (in my case) the panel gets wonky again.

Also, like some of the others mentioned, the problem can be temporarily fixed by turning the extension off and on again.

**Comment by SecMeyo** [comment]
the last update (v64) made this issue worse. It cannot be fixed by reloading the plugin anymore

**Comment by jarek102** [comment]
v65 fixed issue for me
![image](https://github.com/user-attachments/assets/71b9f659-27c4-4432-adf0-278cb5970618)

**Comment by aunetx** [comment]
Hello @sjhaleprogrammer, the bug should be resolved in last commits in the `master` branch, could you try it to tell me if everything works well?

**Comment by SecMeyo** [comment]
installed from master, issue is back to before v64. reload works fine, does not work out of the box in the same way as described above

**Comment by SecMeyo** [comment]
fixed in v66 <3

**Comment by aunetx** [comment]
Thanks for the info @SecMeyo!
