### ISSUE TITLE
Extension bug "actor is null" with a different theme

### ISSUE THREAD

**Issue by MuhammedTaha02** [aunetx/blur-my-shell#51]
Hello. I installed this extension. But extension not opening. And i look #37. It looks the same as my problem.

![image](https://user-images.githubusercontent.com/62564400/115942209-bd7a2f00-a4b1-11eb-8832-972669109463.png)

![image](https://user-images.githubusercontent.com/62564400/115942228-dbe02a80-a4b1-11eb-96e3-3c1123252dc9.png)

**Comment by CorvetteCole** [comment]
hey there, do you mind using journalctl to find the logs from around when the last message was maybe? gnome shell usually puts out a crash report at least. Restarting your shell with Alt+F2 and typing r may help troubleshoot this

**Comment by aunetx** [comment]
Could you give me the output of `journalctl /usr/bin/gnome-shell | grep "blur-my-shell"`?
So we can get the errors (and not only the logs produced by the extension itself) :)

By the way, was there anything blurred after enabling (even if it crashed)? And does disabling dash-to-dock makes the extension work?

**Comment by MuhammedTaha02** [comment]
> Could you give me the output of `journalctl /usr/bin/gnome-shell | grep "blur-my-shell"`?
I threw it in the first photo

**Comment by aunetx** [comment]
No, that was not the exact same line sorry... I need with "blur-my-shell", because "Blur my Shell" will not return the errors, only the logs produced by the extension

**Comment by MuhammedTaha02** [comment]
> No, that was not the exact same line sorry... I need with "blur-my-shell", because "Blur my Shell" will not return the errors, only the logs produced by the extension

![image](https://user-images.githubusercontent.com/62564400/115957474-67d27080-a50b-11eb-842b-860c55c793b2.png)

**Comment by npv12** [comment]
I had this exact issue which turned out to be theme related for some reason. Changing the theme back to its default helped me. Furthermore, even though it said "actor is null" for me, it would still apply fine for some parts. however some other were messed up

**Comment by aunetx** [comment]
Thanks for the replies, I don't really know why the theme would change this part of the dash... I guess I could make the extension ignore this bug (so it does not crash anymore), but I don't know if that's a good idea if there is no real fix, as it may introduce some icons that have artefacts

I will see what I can do, by the way which theme did you use and that made it crash?

**Comment by MuhammedTaha02** [comment]
> Thanks for the replies, I don't really know why the theme would change this part of the dash... I guess I could make the extension ignore this bug (so it does not crash anymore), but I don't know if that's a good idea if there is no real fix, as it may introduce some icons that have artefacts
> 
> I will see what I can do, by the way which theme did you use and that made it crash?

I using flat remix theme. But the plugin never opened for me

**Comment by npv12** [comment]
> Thanks for the replies, I don't really know why the theme would change this part of the dash... I guess I could make the extension ignore this bug (so it does not crash anymore), but I don't know if that's a good idea if there is no real fix, as it may introduce some icons that have artefacts
> 
> I will see what I can do, by the way which theme did you use and that made it crash?

It is very weird for me as well, to see the extension work just after I changed my theme xD. I switched from sweet-dark to adwaita on GNOME 40 and voila, it was working as intended

**Comment by aunetx** [comment]
Last commit may have fixed the crash, but it is actually just a quick fix, the extension still not really support different themes...

**Comment by aunetx** [comment]
Does this bug still happen with last commit?

**Comment by npv12** [comment]
No i cannot recreate it now. Seems like it is fixed :)

**Comment by aunetx** [comment]
Ok cool! I will let the issue open for the moment, but maybe close it at some time... I don't plan to support every possible themes anyway, and will only test the extension with adwaita so I don't intend to fully fix the issue, just remove the crashes!

**Comment by aunetx** [comment]
Well, I prefer to close it as it is not crashing anymore so I can better see what to focus on... Reopen if some issues are still happening please

**Comment by Razer0123** [comment]
Just installed the extension and  having this problem, is the fix online in the Gnome Extensions website?

**Comment by Diegovisk** [comment]
This happened to me with default theme & Dash To Dock. Is there a way to use both? The error is below:

```
Nov 04 21:19:14 fedora gnome-shell[2775]: [Blur my Shell] enabling extension...
Nov 04 21:19:14 fedora gnome-shell[2775]: [Blur my Shell] blurring top panel
Nov 04 21:19:14 fedora gnome-shell[2775]: [Blur my Shell] blurring dash
Nov 04 21:19:14 fedora gnome-shell[2775]: [Blur my Shell] searching for dash
Nov 04 21:19:14 fedora gnome-shell[2775]: [Blur my Shell] dash to dock found, blurring it
Nov 04 21:19:14 fedora gnome-shell[2775]: clutter_actor_get_child_at_index: assertion 'index_ <= self->priv->n_children' failed
Nov 04 21:19:14 fedora gnome-shell[2775]: JS ERROR: Extension blur-my-shell@aunetx: TypeError: actor is null
                                          connect@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/connections.js:33:18
                                          blur_dash_from@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:145:26
                                          try_blur@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:85:35
                                          blur_existing_dashes/<@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:74:18
                                          blur_existing_dashes@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:73:37
                                          enable@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/dash_to_dock.js:66:14
                                          enable@/home/warlock/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/extension.js:49:37
                                          _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                          loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
```
**Gnome version:**
```
<gnome-version>
 <platform>41</platform>
 <minor>1</minor>
 <micro>0</micro>
 <distributor>GNOME.Org</distributor>
 <date>2021-11-02</date>
</gnome-version>
```
**And fedora 35**

I am also using more than one display. Not sure if this is important.

**Comment by Diegovisk** [comment]
Oh, I have un-checked the "dock" option on the app configuration and it worked! That's enough for me :)
