### ISSUE TITLE
Panel disappears when used with Just Perfection

### ISSUE THREAD

**Issue by gianmarcotoso** [aunetx/blur-my-shell#572]
I've found an issue when using this extension alongside Just Perfection, specifically when hiding the panel from the Desktop mode and showing it only in overview mode.

When Blur My Shell is enabled, everything appears to work regularly at first, but after a while the panel in overview mode disappears, but only visually: clicking where the items are supposed to be brings up their respective popups. 

I haven't been able to pinpoint exactly _when_ the panel disappears (I'll update the issue if I find out), but I've noticed that disabling and re-enabling Blur My Shell brings back the panel for a while. Also, this did not happen before the latest update. I should also note that I've tried disabling the "Panel Blur" option to no avail.

Is there some logs I can share to help with this?

**Comment by user1-github** [comment]
I have the same issue since the latest update and I'm also using Just Perfection specifically to disable the panel on the desktop and keep it enabled in overview.

But in my case the panel disappears after each reboot and then if I disable and enable Blur my Shell, it becomes visible without disappearing anymore until the next reboot.

**Comment by aunetx** [comment]
Thanks for the heads-up, I will try with just perfection! I'm using hidetopbar with  no problem but I guess they do not use the same hiding technique

**Comment by XolbyNax** [comment]
## Summary

3 or 4 days ago, after a sudo pacman -Syu, the panel became invisible, but still interactable in the overview. When deactivating the panel in the visibility menu, it also is invisible in the overview, even though it should be visible. 
## Steps to reproduce

Just by disabling Blur my Shell the panel returns without needing to log out. Enabling it again doesn't make the panel disappear until logging out or restarting.

Go to visibility menu, 
disable panel toggle,
enable Blur my Shell extension, 
log out, log in.

## What is the current bug behavior?

Panel is invisible in desktop and overview, with only the searchbar remaining.

## What is the expected correct behavior?

Panel is invisible in desktop, and visible in overview.

## Other Enabled Extensions

I had Blur my Shell with default settings, and this is the conflicting extension. I also had wiggle, but it doesn't do anything.

## Versions

Blur my Shell v60
Just perfection v28
Gnome 46
Arch with kernel Linux 6.8.5-arch1-1

**Comment by XolbyNax** [comment]
I was told by the Just Perfection dev from girlab to come report it here, so, here i am.
Shame I wasn't the first here too.

**Comment by XolbyNax** [comment]
> Thanks for the heads-up, I will try with just perfection! I'm using hidetopbar with no problem but I guess they do not use the same hiding technique

Big boss, can you have a word with the other fella and see if you can figure something out?
https://gitlab.gnome.org/jrahmatzadeh

**Comment by XolbyNax** [comment]
> Thanks for the heads-up, I will try with just perfection! I'm using hidetopbar with no problem but I guess they do not use the same hiding technique

Btw, I am using your default config for BmS, and I deactivated all other extensions, but hidetopbar doesn't do anything for me. I haven't tried logging of and in yet. Give me a moment.
X11 
Gnome 46
Arch with kernel Linux 6.8.5-arch1-1
X Server 1.21.1.13
X Protocol Version 11

**Comment by XolbyNax** [comment]
> Thanks for the heads-up, I will try with just perfection! I'm using hidetopbar with no problem but I guess they do not use the same hiding technique

Btw, I am using your default config for BmS, and I deactivated all other extensions, but hidetopbar doesn't do anything for me. I have tried logging of and in.
X Server 1.21.1.13
X Protocol Version 11
Gnome 46
Arch with kernel Linux 6.8.5-arch1-1

**Comment by gianmarcotoso** [comment]
> Thanks for the heads-up, I will try with just perfection! I'm using hidetopbar with no problem but I guess they do not use the same hiding technique

I've been able to reproduce it consistently:

- Load a Gnome Session with Just Perfection and Blur My Shell enabled
- Disable the panel in desktop mode and enable it in overview from within Just Perfection's options
- Lock the screen
- Unlock the screen and enter the password
- See the panel disappear from overview
- Disable Blur My Shell -> the panel reappears
- Lock the screen, repeat

**Comment by jrahmatzadeh** [comment]
@aunetx Just Perfection extension [removes the panel from the layout and moves it to the overview](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/blob/22d7fbc7431adcc3d709bbd0ecba207e9479c5c2/src/lib/API.js#L408-411).

When the panel is only available in overview (`PANEL_HIDE_MODE.DESKTOP`) it gives a little `margin-top` to the first element in overview.

Also, [these CSS styles](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/blob/22d7fbc7431adcc3d709bbd0ecba207e9479c5c2/src/stylesheet.css#L185-193) are getting applied to the Shell when the panel is hidden.

[As I explained here](https://youtu.be/5IPtmicryVQ?feature=shared&t=12), we made it like this to make it more touch friendly.

Let me know if you need more info on this or if you need specific update on the Just Perfection extension to fix the compatibility issue.

**Comment by gianmarcotoso** [comment]
> Waiting that, I guess affected users should be able to just disable panel blur and everything should be working right (minus the panel being blurred of course)

I have tried disabling panel blur but it does not appear to have any effect, so the bug probably comes from some other code path. Anyway, thank you! :)

**Comment by mgamigo** [comment]
Just to add to the discussion, I am currently suffering this bug too, but just disabling and reenabling the extension fixes the problem for me. So I guess is not a mayor conflict between both extensions.

**Comment by ntruter42** [comment]
Any progress on this? I had to create a workaround in the meantime.

I have to run a script which restarts Blur My Shell every 30 minutes in order to keep the panel visible, because I couldn't find out what stopped it periodically. I had an issue initially, because crontab didn't support files with a dot in it in Ubuntu, so I had to rename it to startup_script. It kinda works now, but it's a terrible workaround.

*/30 * * * * /bin/bash/ /home/ntruter42/startup_script

Only problem now is that every 30 minutes, my system has a 1 second "hiccup" (momentary freeze) to restart the extension. Anyone know of a better workaround for Ubuntu, while we wait for it to be fixed?

**Comment by mgamigo** [comment]
@ntruter42 , why run the script every 30 minutes and not just at startup? You can just add the script to the startup using gnome tweaks. Can you share the code for restarting the extension? I would like to try this solution.

**Comment by ntruter42** [comment]
It's not much, just:
```
gnome-extensions disable blur-my-shell@aunetx
gnome-extensions enable blur-my-shell@aunetx
```

I initially tried to run it only at startup, but I noticed that it still occasionally disappears after a while. I can't figure out what causes it to disappear. I guess I could run the script every hour instead of every 30 minutes.

**Comment by fxzxmicah** [comment]
My panel hasn't disappeared, but there are indeed compatibility issues.

**Comment by user1-github** [comment]
@aunetx Any news regarding the fix to this bug?

I've also noticed a [duplicate](https://github.com/aunetx/blur-my-shell/issues/595).

**Comment by aunetx** [comment]
@user1-github sorry for the delay! I've just looked again into it, it should be quite simple to fix this actually :) so maybe in a few minutes that will be done!

**Comment by aunetx** [comment]
That's done! I've fixed it in last commit, I will create a new release soon (maybe after fixing some other bugs because else I could release things every hour hehe)

@jrahmatzadeh by the way, I noticed that [the `margin-top` calculation](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/blame/22d7fbc7431adcc3d709bbd0ecba207e9479c5c2/src/lib/API.js#L418) seems wrong when the monitor has scaling (or at least clearly is on my 200% scaled monitor); you may need to divide `marginTop` by the scaling of the monitor (the style applied for me is 58px but it seems normal at 26px; I guess the CSS pixel count is made aware of the scaling but `this._main.panel.height` is not).

**Comment by jrahmatzadeh** [comment]
> @jrahmatzadeh by the way, I noticed that [the `margin-top` calculation](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/blame/22d7fbc7431adcc3d709bbd0ecba207e9479c5c2/src/lib/API.js#L418) seems wrong when the monitor has scaling (or at least clearly is on my 200% scaled monitor); you may need to divide `marginTop` by the scaling of the monitor (the style applied for me is 58px but it seems normal at 26px; I guess the CSS pixel count is made aware of the scaling but `this._main.panel.height` is not).

[Fixed](https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/commit/1d77778774c132e2256f0edaaa857f52355cec48).

**Comment by leonidx86** [comment]
The bug still exists.
Blur my Shell - version 67.
Just Perfection - version 30.

**Comment by ntruter42** [comment]
> The bug still exists. Blur my Shell - version 67. Just Perfection - version 30.

The bug was fixed in a commit made on Sep 15, but the last release is from Sep 14. We need to wait for the next release in order to get the fix. I think it should have been released already, without or without other updates to add. The hotfix is worth a new release, even if it can be versioned 67.0.1 or something like that.

[Message stating that the issue was fixed, but will be released later](https://github.com/aunetx/blur-my-shell/issues/572#issuecomment-2351632528)

[Commit where the problem was fixed](https://github.com/aunetx/blur-my-shell/commit/b39c53630ef16384dfb567894bffd50afd76d469)

[Current release (without fix applied)](https://github.com/aunetx/blur-my-shell/releases/tag/v67)
