### ISSUE TITLE
LibAdwaita/GTK4 app blur on Wayland

### ISSUE THREAD

**Issue by certifiedfoolio** [aunetx/blur-my-shell#634]
I don't know if this is an extension issue, a LibAdwaita/GTK4 issue, or a Wayland issue, but might as well post here. Blur on LibAdwaita/GTK4 apps simply does not work on Wayland; the transparency is shown but blur is not applied. Blur is applied to non-LibAdwaita/GTK4 apps, however. On X11/Xorg, there is blur on every app including LibAdwaita/GTK4 ones and nothing is wrong. Help?

Comparison w/ Steam (non-gtk4) and Nautilus (gtk4):
![Screenshot from 2024-08-16 07-06-35](https://github.com/user-attachments/assets/74219129-5787-474d-a02c-1751ffb1d374)

**Comment by certifiedfoolio** [comment]
Using the latest version of Blur My Shell (via extension manager) and Gnome 46.3.5 on Nobara 40.

**Comment by l3ifk** [comment]
Can confirm this is the same for me on Ubuntu 24.04 with Gnome 46. Xorg does work but wayland makes problems ...

**Comment by certifiedfoolio** [comment]
@aunetx thoughts?

**Comment by titov51** [comment]
Same here, I'm on arch latest

**Comment by certifiedfoolio** [comment]
Aha! This seems to be something with NVidia drivers. Was installing NixOS and tried application blur again, it worked. Installed my NVidia drivers and we are back to this issue.

**Comment by certifiedfoolio** [comment]
I am completely wrong. Upon further experimentation, the non-working blur seems to be some kind of conflict with the "Rounded Corners Reborn" extension. Disabling it fixes this issue. @titov51 @l3ifk

**Comment by certifiedfoolio** [comment]
I do not know if the issue reappears in "conflicts" with other extensions at the moment, if you DO find one please post here.

**Comment by certifiedfoolio** [comment]
why did i close this, mb
is there going to be a fix for the conflict soon?

**Comment by l3ifk** [comment]
yeah not really surprise because I had problems where these two extensions conflicted back when upgrading from Ubuntu 23.10 to 24.04.
This was fixed but it seems like there still is a conflict :/ What is still weird though is that with X11 all this is no problem but wayland makes prpblems... If I'll figure anything out I will update here

**Comment by certifiedfoolio** [comment]
i have no experience in this field, but.. maybe the way windows are drawn conflicts?

**Comment by certifiedfoolio** [comment]
also, blacklisting LibAdwaita and LibHandy apps from being affected via the extension's settings still doesnt fully fix this issue; Firefox still seems to be affected, so may some other apps.

**Comment by aunetx** [comment]
Hello all, sorry for the delay, there is no fix coming very soon (the dynamic blur effect used by blur-my-shell is entirely incompatible with any other effect, including the ones used by the rounded windows corner extension...).

This will only be fixed when I finally port the pipelines static blur onto the applications blur, which may or may not be in the next weeks to be honest :)

**Comment by Schneegans** [comment]
Hi everyone! I [may have figured out a fix / workaround](https://github.com/flexagoon/rounded-window-corners/pull/77) for this on the rounded-corners-extension side.

Although I do not fully understand why some code was there which I had to remove... Maybe you guys could give this PR a test and see if this works on your end? For me, it works now both on Wayland and X11.

The only remaining issue seems to be that corners of the blurred background are not round, but this is not too noticeable, I think.

**Comment by momoRaza** [comment]
@Schneegans I tried it on wayland, it seems to work fine as long as the scaling is 100 %

https://github.com/user-attachments/assets/695a6d64-277f-412d-b470-d872926f138a

**Comment by certifiedfoolio** [comment]
> [@Schneegans](https://github.com/Schneegans) I tried it on wayland, it seems to work fine as long as the scaling is 100 %
> 
>  Screencast.From.2025-02-02.18-35-04.webm

can you try closing and reopening the window?

**Comment by momoRaza** [comment]
@Schneegans @certifiedfoolio Correction, I tried it in a vm which is why it was causing an issue, after installing it on my main system it seems to be working fine.

**Comment by Schneegans** [comment]
> [@Schneegans](https://github.com/Schneegans) [@certifiedfoolio](https://github.com/certifiedfoolio) Correction, I tried it in a vm which is why it was causing an issue, after installing it on my main system it seems to be working fine.

Interesting. However, I observed some issues as well when scaling is involved. I think they can be resolved as the issues are gone one a window is resized, so I think we only need to trigger some callback after a window is shown. But I currently have not the time to look into it 😟
