### ISSUE TITLE
Small gap between top panel and window

### ISSUE THREAD

**Issue by Calosis** [aunetx/blur-my-shell#650]
Commit: 7678368ce30f9dacdcfad8693a46340aafc8b07a

Applying the commit above causes a small gap to appear between the top panel while blurred and any window sitting underneath it. This is due to their being a ``z_position`` of ``1``. Reverting the value to 0 gets rid of the issue.

Maybe this should be a toggle? If you want to apply the fix, you can then deal with this small annoyance.

![fXtQoX5](https://github.com/user-attachments/assets/3d7e7238-63f0-4321-88b9-b010fa93b590)

**Comment by aunetx** [comment]
Thanks for opening this, I noticed it but was not sure it was because of this commit, that's a bit weird (and coincidentally, I don't have any idea what z-position does but to fix my issue so maybe it is normal after all).

I will test it an see if the gap is present no matter what the configuration is, and if so then I will probably adapt the size of the blur instead to add an extra pixel (because having a toggle to fix a bug can be a bit special for some people).

By the way, did you notice it happening at some other place? I noticed once the overview blur overflowing to the next display but that has not happened again, so I guess it was another bug than this one (which is not so good hehe).

**Comment by aunetx** [comment]
Well, else I can just apply the fix only if there are multiple monitors, that's not too bad!

**Comment by Calosis** [comment]
> Thanks for opening this, I noticed it but was not sure it was because of this commit, that's a bit weird (and coincidentally, I don't have any idea what z-position does but to fix my issue so maybe it is normal after all).
> 
> I will test it an see if the gap is present no matter what the configuration is, and if so then I will probably adapt the size of the blur instead to add an extra pixel (because having a toggle to fix a bug can be a bit special for some people).
> 
> By the way, did you notice it happening at some other place? I noticed once the overview blur overflowing to the next display but that has not happened again, so I guess it was another bug than this one (which is not so good hehe).

I haven't noticed any other issues/gaps other than the top panel.

I'd assume more people would complain about the pixel gap than the multi monitor blur bug.

**Comment by aunetx** [comment]
Hello @Calosis, the last commit seems to fix this without any side-effect, would you mind trying it? :)

**Comment by Calosis** [comment]
> Hello @Calosis, the last commit seems to fix this without any side-effect, would you mind trying it? :)

Thank you for looking into this. The gap seems to be gone now. I will update you if I find any issues in the next day or two.

**Comment by Calosis** [comment]
> > Hello @Calosis, the last commit seems to fix this without any side-effect, would you mind trying it? :)
> 
> Thank you for looking into this. The gap seems to be gone now. I will update you if I find any issues in the next day or two.

Durning the past 2 days I have not experienced any issues and blur works 100% of the time now.

**Comment by d3vilguard** [comment]
66 is the last commit, right? Doesn't fix it for me.

**Comment by iamaakashbasnet** [comment]
No fix for me too
![Screenshot from 2024-09-14 20-41-51](https://github.com/user-attachments/assets/6d3cfa54-40df-437c-ba7a-337f62b6da34)

**Comment by aunetx** [comment]
Hello @d3vilguard and @iamaakashbasnet, could you test it from the last commit? It must be fixed now but I'm not entirely sure

**Comment by d3vilguard** [comment]
I'm doing the manual install, pulling the latest git from here.

**Comment by aunetx** [comment]
It's weird, it looks like it was fixed for others... I keep this open but I will push the fix in the release, if that works in the next days don't hesitate to tell me @d3vilguard!

(by the way, what is your screen scaling? it may be related to it...)

**Comment by d3vilguard** [comment]
Glorious 125% fractional. But going to 100% doesn't solve it. Only going to Dynamic. Till now Static had no problems for me.

**Comment by iamaakashbasnet** [comment]
Choosing dynamic seems to fix the issue for me, for static problem still exist.
![Screenshot from 2024-09-14 23-51-06](https://github.com/user-attachments/assets/96139d99-566c-4f22-8739-84010d77ad6d)

**Comment by aunetx** [comment]
Huh, it may be because of fractional scaling... @iamaakashbasnet which scaling do you use?

**Comment by iamaakashbasnet** [comment]
I use default 100% scaling
![Screenshot from 2024-09-14 23-54-49](https://github.com/user-attachments/assets/fc5fffd4-988f-4c0e-bf5e-c7c3ea879b34)

**Comment by iamaakashbasnet** [comment]
@aunetx v67 seems to be the fix! Thanks! :)

**Comment by d3vilguard** [comment]
v67, Static, 125% fractional - all good.

**Comment by aunetx** [comment]
Cool thanks a lot!
